FROM python:3.13-slim
WORKDIR /app

COPY pyproject.toml /app/

RUN pip install --upgrade pip && \
    pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

COPY api /app/api

EXPOSE 8001
# Remove --reload for production
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8001"]
